export { CSSIcon as CssIcon } from "./CSS"
export { NodeJSIcon as NodeIcon} from "./NodeJS"
export { NextJSIcon as NextIcon} from "./Next"
export { ReactIcon as ReactIcon} from "./React"
export { PostCSSIcon as PostCssIcon} from "./PostCSS"
export { HTMLIcon as HtmlIcon} from "./HTML"
export { TailwindIcon as TailwindCssIcon} from "./Tailwind"
